#DICTIONARY

DATA = {
    "AGING" : "The reductionof insulation life due to thermal, voltage and other stress.",
    "AIR GAP" : "Short gp in the magnetic material forming a magnetic circuit.",
    "BRUSH" : "A sliding electrical contact , usually rotating.",
    "CAPACITANCE" : " The amount of electrical energy stored for a given electrical potential.",
    "COIL" : "Set of series of connected turns.",
    "DATA BLOCK" : "A sequence of data in bits or bytes that are usually transferred as a whole.",
    "DIGITAL" : "A system in which all the information and signals are represented either by binary numbers or discrete values.",
    "EARPHONE" : "A small piece of equipment that converts electrical waves into sound waves.",
    "ELECTROMETER" : "A voltage measuring instrument that measures the electrical potential difference between two charged bodies without drawing any current from the source or circuit.",
    "FAILURE" : "The malfunctioning of a device or a component that does not achieve the desired target.",
    "GAMMA" : "A unit of magneTic intensity equal to 10-5 oersted.",
    "HALT" : "A command that is used to stop n operation either permanently or temporarily.",
    "IMPLOSION" : "It is the sudden inward collapse.",
    "JACK SCREW" : "A screw-operated jack for lifting, exerting pressire, or adjusting position.",
    "KEYBOARD" : "A peripheral device that is used as data inpur for a computer.",
    "LADDER" :  "A circuit structure using components connected in a chain.",
    "MASKING": "A process in which only required data is retained and the rest is blocked, it can be done using bitwise operators.",
    "NEGATE" : "In Boolean algebra, Negate means complement.",
    "OBSOLETE" : "These are products which are no longer manufactured or discontinued due to replace of products by advanced function.",
    "PART" : "A single component/device or a permanent assembly of more than one part that is intended to be a part of something else.",
    "QUINT" : "A sequence of five individual circuit blocks within the same IC package.",
    "RADIAN" : "A unit of angular measurement that is equal to the lenth that corresponds to the unit circle. 1rad = 57.3degrees.",
    "SATELLITE" : "An artificial celestial body that placed in orbit round the planet in order to collect information or to establish better ommunication network.",
    "TAP" : "A fixed intermediate point in an electrical from which connections can be made.",
    "UNIT" : "A single device or a group of devices that can operate itself and can also be assembled together to execute a more complex operation.",
    "VACUUM" : "An enclosed area of space that is relatively empty of matter.",
    "WAVE" : "A pattern of disturbance generated by the movement of energy propagating through a medium from one location to another.",
    "X-AXIS" : "The principal or horizontal axis of a system of coordinates, points along which have value of zero for all other coordinates.",
    "Y-AXIS" : "A vertical reference axis in a two dimensional coordinate system/graph.",
    "ZERO POTENTIAL" : "The potential across the ground terminal in any electrical circuit."
    
    }

a = input("SEARCH:")
print(DATA[a])
    